### ISSUE TITLE
Triggers don't work

### ISSUE THREAD

**Issue by Whireking** [FricoRico/Homey.SonyBraviaAndroidTV#7]
I don't get any triggers working in the flows with my TV. If I want to make a trigger based on the TV being Turned On nothing happens. It doesn't matter if I turn on the TV with the Homey App or the Remote Control. The flow isn't started.
I have tried them all the triggers and none work. Actions are working correctly.
I am using Homey 2.0.2 and have the Sony KD-49X8305C from 2015.

**Comment by FricoRico** [comment]
This is an interesting one. Let's start by explaining the two cases where `Turned on` and `Turned off` events can trigger:

- Every few minutes (depends on your settings) Homey will make a request to the television to see if it's turned on or off with the remote. The polling is required because the TV is `dumb` it can not report to Homey itself when it's turned on or turned off. This might be resolved when I release an accompanying Android TV app in the Play Store, but for now it's polling.
- The other case is when you use the Homey controls to boot up the TV. This should be instant and the trigger is entirely controlled by Homey itself (it's not a custom trigger, but linked to the `onoff` capability, which also creates the button itself).

Strangely enough the Homey direct trigger is no longer working. This worked fine before releasing the alpha. The polling nicely triggers the `Turned on` and `Turned off` triggers accordingly.

For the other triggers (like `HDMI Changed` and `Numpad input`) I can be very short. They only work if you change the input from Homey flow actions themselves. They can not be 'asked' like the power state can through the API. This can also only be fixed by implementing them in an Android app (if it can be accessed from the Android SDK).

**Comment by FricoRico** [comment]
Issue should be resolved with app version **1.0.2**. Can you please confirm?

**Comment by Whireking** [comment]
Thank you for your explanation. 
Didn't think of the polling when writing this issue. On the 1.0.1. version I put it to 1 min and waited, after that the On / Off trigger worked. The direct triggers started working on version 1.0.2.

I noticed another thing related to this. If I turn the tv on / off with the remote control. In the Homey app the button state under Devices doesn't change. If the tv is turned off with remote it stays on, if turned on it stays off. Even after the polling time exceeded. It changes the moment I long press the button and go back out of the button again, but not by itself.

**Comment by FricoRico** [comment]
I'm sorry to hear you are seeing issues with the powerbutton. I just tested it and checked it with my Sony BRAVIA television and it is synchronous with the flow trigger (used speak to test) and the polling. The button changes from white to black appropriately.

Can you make sure the problem persists? I noticed Homey being somewhat buggy on updating the UI, whilst flow triggers are working correctly. If the problem persists please open a new Issue.
